#include <systemlib/param/param.h>

PARAM_DEFINE_FLOAT(VCN_X_KI,0);
PARAM_DEFINE_FLOAT(VCN_X_KP,0);
PARAM_DEFINE_FLOAT(VCN_X_KD,0);
PARAM_DEFINE_FLOAT(VCN_X_MAX,0);
PARAM_DEFINE_FLOAT(VCN_X_ISAT,0);

PARAM_DEFINE_FLOAT(VCN_Y_KI,0);
PARAM_DEFINE_FLOAT(VCN_Y_KP,0);
PARAM_DEFINE_FLOAT(VCN_Y_KD,0);
PARAM_DEFINE_FLOAT(VCN_Y_MAX,0);
PARAM_DEFINE_FLOAT(VCN_Y_ISAT,0);

PARAM_DEFINE_FLOAT(VCN_Z_KI,0);
PARAM_DEFINE_FLOAT(VCN_Z_KP,0);
PARAM_DEFINE_FLOAT(VCN_Z_KD,0);
PARAM_DEFINE_FLOAT(VCN_Z_MAX,0);
PARAM_DEFINE_FLOAT(VCN_Z_ISAT,0);

PARAM_DEFINE_FLOAT(VCN_ROLL_MAX,0);
PARAM_DEFINE_FLOAT(VCN_PITCH_MAX,0);
PARAM_DEFINE_FLOAT(VCN_THRUST_MAX,0);
PARAM_DEFINE_FLOAT(VCN_THRUST_MIN,0);
PARAM_DEFINE_FLOAT(VCN_THRUST_G,0);

PARAM_DEFINE_FLOAT(VXX_W,0);
PARAM_DEFINE_FLOAT(VXX_R,0);

PARAM_DEFINE_INT32(VCN_USE_DELAY,0);
PARAM_DEFINE_INT32(VCN_USE_RBIAS,0);



